app/forms/components.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField
from wtforms.validators import DataRequired, InputRequired

class DateRequestForm(FlaskForm):
    message = StringField(
        "Optional text attached to accept/reject/reschedule", [InputRequired(message="Message can't be empty")]
    )
    date = DateField("Date", format="%Y-%m-%d", validators=[DataRequired()])
    # submit_reject = SubmitField("Reject", widget=LabeledIconSubmitWidget())
    # submit_ignore = SubmitField("Ignore", widget=LabeledIconSubmitWidget())
    # submit_reschedule = SubmitField("Reschedule", widget=LabeledIconSubmitWidget())
    # submit_accept = SubmitField("Accept", widget=LabeledIconSubmitWidget())
    # submit_invite = SubmitField("Invite", widget=LabeledIconSubmitWidget())

    def __init__(self, message_label_text=None, given_date=None, *args, **kwargs):
        super(DateRequestForm, self).__init__(*args, **kwargs)
        if message_label_text:
            self.message.label.text = message_label_text
        if given_date:
            self.date = StringField(label=given_date, render_kw={"readonly": True})

app/forms/date_request_form.py
from flask_wtf import FlaskForm
from wtforms import DateField, HiddenField, StringField
from wtforms.validators import DataRequired, InputRequired, Length

from app.config import MAXIMUM_MESSAGE_LENGTH
from app.forms.validators import is_any_table_available_for_date, is_not_past


class DateRequestForm(FlaskForm):
    id = HiddenField()
    message = StringField(
        "Optional text attached to accept/reject/reschedule",
        validators=[
            Length(
                max=MAXIMUM_MESSAGE_LENGTH, message=f"Message may be at most {MAXIMUM_MESSAGE_LENGTH} characters long"
            )
        ],
    )
    date = DateField(
        "Date", format="%Y-%m-%d", validators=[DataRequired(), is_not_past, is_any_table_available_for_date]
    )

    def __init__(self, message_label_text=True, given_date=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not message_label_text:
            self.message.label.text = ""

        if given_date:
            # Modify the date field properties dynamically instead of replacing it
            self.message.label.text = "Optional text attached to accept/reject"
            self.date.render_kw = {
                "readonly": True,
                "value": given_date.strftime("%Y-%m-%d"),
            }  # Makes the field readonly
            self.date.data = given_date  # Pre-fill the field with the given date
        # self.process()

app/views/auth.py
import json
from functools import wraps

from flask import Blueprint, abort
from flask import current_app as app
from flask import flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required, login_user, logout_user
from sqlalchemy.exc import IntegrityError
from werkzeug.utils import secure_filename

from app import User, db
from app.forms import LoginForm, ProfileManagerForm, RegisterForm
from app.models import Gender, Interest, Photo, Profile
from app.utils import send_email

auth_bp = Blueprint("auth_bp", __name__)


# only allow authenticated users, otherwise redirect to login page
def login_redirect(func):
    @wraps(func)
    def inner(*args, **kwargs):
        if current_user.is_authenticated:
            return func(*args, **kwargs)
        if request.method == "GET":
            return redirect(url_for(app.config["LOGIN_PAGE_ROUTE"]))
        abort(401)

    return inner


# only allow confirmed users, otherwise redirect to unconfirmed/login page
def confirmed_required(func):
    @wraps(func)
    @login_redirect
    def inner(*args, **kwargs):
        if not app.config["ADVANCED_ACCESS_CONTROL"]:
            return func(*args, **kwargs)
        if not current_user.confirmed:
            if request.method == "GET":
                return redirect(url_for(app.config["UNCONFIRMED_PAGE_ROUTE"]))
            abort(401)
        return func(*args, **kwargs)

    return inner


# only allow unconfirmed users, otherwise redirect to main/login page
def unconfirmed_required(func):
    @wraps(func)
    @login_redirect
    def inner(*args, **kwargs):
        if not app.config["ADVANCED_ACCESS_CONTROL"]:
            return func(*args, **kwargs)
        if current_user.confirmed:
            if request.method == "GET":
                return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))
            abort(401)
        return func(*args, **kwargs)

    return inner


# only allow for anonymous (unlogged) users, otherwise redirect to main page
def anonymous_required(func):
    @wraps(func)
    def inner(*args, **kwargs):
        if not app.config["ADVANCED_ACCESS_CONTROL"]:
            return func(*args, **kwargs)
        if not current_user.is_anonymous:
            if request.method == "GET":
                return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))
            abort(401)
        return func(*args, **kwargs)

    return inner

@auth_bp.route("/login", methods=["GET", "POST"])
@anonymous_required
def login():
    form = LoginForm()
    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))
        flash("Invalid username or password. Please try again.", "error")
        return redirect(url_for("auth_bp.login"))

    return render_template("auth/login.html", form=form)


@auth_bp.route("/logout")
def logout():
    if current_user.is_authenticated:
        logout_user()
    return redirect(url_for("auth_bp.login"))


@auth_bp.route("/register", methods=["GET", "POST"])
@anonymous_required
def register():
    form = RegisterForm()

    if request.method == "GET" and "registration_data" in session:
        registration_data = session["registration_data"]
        form.username.data = registration_data.get("username", "")
        form.email.data = registration_data.get("email", "")

    if process_registration_form(form):
        return redirect(url_for("auth_bp.complete_profile"))

    return render_template("auth/register.html", form=form)


@auth_bp.route("/complete-profile", methods=["GET", "POST"])
@anonymous_required
def complete_profile():
    if "registration_data" not in session:
        return redirect(url_for("auth_bp.register"))

    profile_form = initialize_profile_form()

    if process_profile_form(profile_form):
        return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))

    return render_template("auth/complete_profile.html", form=profile_form)


@auth_bp.route("/confirm/<token>", methods=["GET", "POST"])
@unconfirmed_required
def confirm(token):
    if current_user.confirm(token):
        db.session.commit()
        return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))
    flash("The confirmation link is invalid or has expired.")
    return redirect(url_for(app.config["UNCONFIRMED_PAGE_ROUTE"]))


@auth_bp.route("/unconfirmed")
@unconfirmed_required
def unconfirmed():
    return render_template("components/unconfirmed.html")


@auth_bp.route("/resend")
@unconfirmed_required
def resend():
    token = current_user.generate_token()
    confirm_url = url_for("auth_bp.confirm", token=token, _external=True)
    contents = render_template("components/confirmation_email.html", url=confirm_url)
    subject = "Email confirmation"

    send_email(current_user.email, subject, contents)

    return redirect(url_for(app.config["UNCONFIRMED_PAGE_ROUTE"]))


@auth_bp.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for(app.config["MAIN_PAGE_ROUTE"]))
    return redirect(url_for("auth_bp.login"))


def initialize_profile_form():
    profile_form = ProfileManagerForm()
    profile_form.gender.choices = [(gender.name, gender.value) for gender in Gender]
    profile_form.gender_preferences.choices = [(gender.name, gender.value) for gender in Gender]
    profile_form.display_photo = url_for("static", filename=app.config["DEFAULT_PHOTO"])
    return profile_form


def process_registration_form(form):
    if form.validate_on_submit():
        session["registration_data"] = {
            "username": form.username.data,
            "email": form.email.data,
            "password": form.password.data,
        }
        return True
    return False


def process_profile_form(profile_form):
    if profile_form.validate_on_submit() and "registration_data" in session:
        try:
            new_user = create_user_with_profile(session["registration_data"], profile_form)
            if app.config["ADVANCED_ACCESS_CONTROL"]:
                send_confirmation_email(new_user)
            login_user(new_user)
            session.pop("registration_data", None)
            return True
        except IntegrityError:
            db.session.rollback()
            flash("An error occurred while creating your account.")
    return False


def create_user_with_profile(registration_data, profile_form):
    new_user = User(
        username=registration_data["username"],
        email=registration_data["email"],
        password=registration_data["password"],
    )

    new_user.profile = Profile(
        name=profile_form.name.data,
        gender=Gender[profile_form.gender.data],
        description=profile_form.description.data,
        year_of_birth=profile_form.year_of_birth.data,
        interests=[db.get_or_404(Interest, int(single["id"])) for single in json.loads(profile_form.interests.data)],
    )

    new_user.matching_preferences.gender_preferences = [Gender[gp] for gp in profile_form.gender_preferences.data]
    new_user.matching_preferences.lower_difference = profile_form.lower_difference.data
    new_user.matching_preferences.upper_difference = profile_form.upper_difference.data

    db.session.add(new_user)
    db.session.commit()

    if profile_form.photo.data:
        photo = profile_form.photo.data
        handle_photo_upload(photo, new_user)

    return new_user


def send_confirmation_email(user):
    token = user.generate_token()
    confirm_url = url_for("auth_bp.confirm", token=token, _external=True)
    contents = render_template("components/confirmation_email.html", url=confirm_url)
    subject = "Email confirmation"
    send_email(user.email, subject, contents)


def handle_photo_upload(photo, user) -> Photo:

    extension = secure_filename(photo.filename).split(".")[-1]
    new_photo = Photo(profile=user.profile, file_extension=extension)

    db.session.add(new_photo)
    db.session.commit()

    photo.save(new_photo.os_photo_url)

    user.profile.photo = new_photo

    return new_photo

app/views/common.py
from flask import Blueprint, abort, jsonify

from app.models.interest import Interest
from app.views.auth import confirmed_required


common_bp = Blueprint("common_bp", __name__)

@common_bp.route('/interests')
def interests():
    interests = Interest.query.all()
    if not interests:
        abort(404)
    return jsonify({"interests": [{"id": interest.id, "name": interest.name} for interest in interests]})

app/views/profile.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user

from app import User, db
from app.forms.date_request_form import DateRequestForm
from app.views.auth import confirmed_required

profile_bp = Blueprint("profile_bp", __name__)


@profile_bp.route("/profile/<int:user_id>")
@confirmed_required
def profile(user_id):
    date_request_form = DateRequestForm(message_label_text="Optional text attached to invite/reject")
    invite_only = request.args.get('invite_only', default=True)
    user = db.get_or_404(User, user_id)
    if user.id == current_user.id:
        return redirect(url_for("you_page_bp.you_page"))
        
    return render_template("profile.html", user=user, form=date_request_form, invite_only=invite_only)

app/templates/components/button.html
{% block content %}
<a
  href="{{ url }}"
  class="orange-button gap-top-15"
  style="
  width: {{ width }}; 
  font-size: {{ font_size }}; 
  background-color: var(--primary-color);
  padding: 5px;
  "
  {% if id is defined%} id="{{ id }}" {% endif %}
  
>
  {{ text }}</a
>
{% endblock %}

app/templates/components/confirmation_email.html
<p>Thanks for signing up to our site! To confirm your registration, click on the link below</p>
<p><a href="{{ url }}">{{ url }}</a></p>
<p>Keep in mind that the link will only remain viable for an hour since it was sent. If the link has expired, log in to our site to send another.</p>
<p>If you did not sign up to our site, please ignore this message. We apologise for the inconvenience.</p>

app/templates/components/date_request.html
{% block content %}

<div
        class="invitation-form-tile centered-column outline fill-width push-to-bottom"
        id="date-request-tile"
>
    <h2 class="primary-color">Date?</h2>
    <!--TODO: implement the date part here in js perhaps-->
    <hr/>
    <p>at Malvarosa 4, Madrid</p>
    <form type="submit" class="centered-column fill-parent" id="invite-form">
        {{ form.csrf_token }}
        <div class="gap-top-15"></div>
            <div class="push-to-bottom centered-column fill-width">
                {{form.id(id='id-hidden')}}

                {% if not is_requesting %}
                <textarea id="message-inbound" disabled></textarea>
                {% endif %}

                {{ form.message.label }}
                {{ form.message(id='message-input') }}
                <ul class="errors" id="message-errors">
                </ul>
                <label>Select a date:</label>
                {{ form.date(id='date-input', readonly=(not is_requesting)) }}
                <ul class="errors" id="date-errors">
                </ul>
                <div class="gap-top-15"></div>
                {% if is_requesting %}
                <ul class="push-to-bottom row space-between centered fill-width">
                    {% if invite_only %}
                    <div class="centered-column fill-width">
                        <li>
                            <div class="labeled-icon" id="invite"><i class="fas fa-heart"></i>Invite</div>
                        </li>
                    </div>
                    {% else%}
                    <li>
                        <div class="labeled-icon" id="reject"><i class="fas fa-times"></i>Reject</div>
                    </li>
                    <li>
                        <div class="labeled-icon" id="invite"><i class="fas fa-heart"></i>Invite</div>
                    </li>
                    {% endif %}
                    
                </ul>
                {% else %}
                <ul class="push-to-bottom row space-around fill-width">
                    <li>
                        <div class="labeled-icon" id="reject-invitation"><i class="fas fa-times"></i>Reject</div>
                    </li>
                    <li>
                        <div class="labeled-icon" id="ignore"><i class="fas fa-heart-broken"></i>Ignore</div>
                    </li>
                    <li>
                        <div class="labeled-icon" id="reschedule"><i class="fas fa-clock"></i>Reschedule</div>
                    </li>
                    <li>
                        <div class="labeled-icon" id="accept"><i class="fas fa-heart"></i>Accept</div>
                    </li>
                </ul>
                {% endif %}
            </div>
    </form>
</div>


{% endblock %}

app/templates/components/form_input.html
{{ input.label }}
{{ input(value=val) }}
{% if input.errors %}
    <ul class="errors">
    {% for error in input.errors %}
        <li>{{ error }}</li>{% endfor %}
    </ul>
{% endif %}

app/templates/components/interests_choosing.html
<!-- 
 IMPORTANT!!!!
 pass the interests as with interests, you dont have to pass interests
 if they are empty
 -->

{% block component %}
<link rel="stylesheet"
              href="{{ url_for('static', filename='style.css') }}">
<meta id="interests-path" data-path="{{ url_for('common_bp.interests') }}">

<input id="interests" type="hidden" name="interests" value=""/>
<label>Interests</label>
<div  class="input-field outline">
    <div class="padding-all-15">
        <div>
            <i class="fas fa-arrow-left" onclick="cancel()"></i>
            <i class="fas fa-check" onclick="acceptInterests()"></i>
        </div>
        <h6>Chosen: </h6>
        <ul class="chosen-interests gap-top-15">
        </ul>
        <br>
        <h6>Choose more: </h6>
        <ul class="to-be-chosen-interests gap-top-15">
        </ul>
    </div>
</div>
<!-- TODO: remove after intergrating into some base-->
<script src="{{ url_for('static', filename='scripts.js') }}"></script>
<script
            src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>  
<script>
    var selectedInterests = []
    {% for interest in interests %}
        selectedInterests.push({'id': parseInt('{{ interest.id }}'), 'name': '{{ interest.name }}'})
    {% endfor %}
    
</script>
<script src="{{ url_for('static', filename='interests_choosing.js')}}"></script>
<script>
    init()
</script>



{% endblock %}

app/templates/components/no_matches_found.html
{% block content %}
<div class="centered-column solo-centered-column-under-top-bar">
    <h1>Ups! it seems like we couldn't find any date for you</h1>
    <p>maybe lower your standards...</p>
</div>
{% endblock %}

app/templates/components/profile_brief.html
{% block content %}

<div class="profile-brief centered-column outline shadow">
    <img src="{{ user.profile.profile_picture_url_or_default }}" class="profile-brief-photo gap-top-15"/>
    <h2 class="text-shadow">{{ user.profile.name }}</h2>
    <p>{{ user.profile.description }}</p>
    
    {% with url=url_for('profile_bp.profile', user_id=user.id), text='See More', width='100px', font_size='medium' %}
    {% include 'components/button.html' %}
    {% endwith %}
<div class="gap-top-15">    </div>
    {% if proposal is defined %}
    <div class="outline push-to-bottom fill-width scaffold-background-color ">
        <div style="gap: 10px" class="centered-column padding-all-15">
            <p class="primary-color" >{{ proposal.just_date }}</p>
            <hr class="fill-width"/>
            <p>{{ proposal.proposal_message }}</p>
            {% if proposal.response_message %}
            <hr class="fill-width"/>
            <p>{{proposal.response_message}}</p>
            {% endif %}
        </div>
        {% if proposal.proposer.id == current_user.id %}
        <label class="padding-all-15 light-color">{{ proposal.ignored_safe_status }}</label>
        {% else %}
        <label class="padding-all-15 light-color">{{ proposal.status.name }}</label>
        {% endif %}
    </div>
    {% endif %}
</div>

{% endblock %}

app/templates/components/profile_button.html
{% block content %}
<a
  href="{{ url }}"
  class="redirect-buttons-set-button gap-top-15"
  style="
  width: {{ width }}; 
  font-size: {{ font_size }}; 
  background-color: var(--primary-color);
  padding: 5px;
  "
>
  {{ text }}</a
>
{% endblock %}

app/templates/components/profile_field.html
{% block content %}
    <div class="profile-field fill-width padding-all-15">
        <label class="profile-field-label padding-all-5">{{ label }}</label>
        {% if values is defined %}
            <div class="outline fill-width padding-all-15 shadow keyword-soaps-layout">
                {% for value in values %}
                    <div class="keyword-soap">{{ value }}</div>
                {% endfor %}
            </div>
        {% else %}
            <div class="outline fill-width padding-all-15 shadow">
                <p class="profile-field-value">{{ value }}</p>
            </div>
        {% endif %}
        
    </div>
{% endblock %}

app/templates/components/set_of_pull_buttons.html
{% block content %}
    <div class="pull-buttons-set">
        {% for data in pull_buttons_set_data %}
                <a class="pull-buttons-set-button {{ data.jsCallBackIndicator }} {% if loop.index == 1 %}active-background{% endif %}">
                    {{ data.text }}
                </a>
        {% endfor %}
    </div>
{% endblock %}

app/templates/components/set_of_redirect_buttons.html
{% block content %}
    <div class="redirect-buttons-set light-shadow">
    {% for data in redirect_buttons_set_data %}
        <a href="{{ data.url }}" class="redirect-buttons-set-button">{{ data.text }}</a>
    {% endfor %}
    </div>
{% endblock %}

app/templates/components/this_list_is_empty.html
{% block content %}
<div class="centered-column solo-centered-column-under-top-bar">
    <h1>Ups! This list seems to be empty</h1>
    <p>get your game on dude...</p>
</div>
{% endblock %}

app/templates/components/unconfirmed.html
{% extends 'main/base.html' %}

{% block content %}
<div class="solo-centered-column-under-top-bar about-us" >
    <p>It seems your account has not been activated yet! You should have received an email with a link allowing you to activate your account and begin using our service!</p>
    <p>If you have not received an email, or the activation link has alread expired, click <a class="link" href="{{url_for('auth_bp.resend')}}">here</a> to resend the email.</p>
    {% with messages = get_flashed_messages() %}
        {% for message in messages %}
            <div>{{ message }}</div>
        {% endfor %}
    {% endwith %}
</div>
{% endblock %}

app/templates/components/users_profile_briefs.html
{% for user in users %}
    {% include 'components/profile_brief.html' %}
{% endfor %}