app/auth.py
from flask import Blueprint, request, redirect, url_for, render_template
from flask_login import login_user, login_required, logout_user, current_user

from . import db, User
from .forms import LoginForm, RegisterForm

auth_bp = Blueprint('auth_bp', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data
        
        print(username)

        # Find user by username
        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('dashboard_bp.dashboard'))
        return "Invalid credentials", 401

    return render_template('login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():

        username = form.username.data
        password = form.password.data
        email = form.email.data

        # Create new user
        new_user = User(username=username, email=email)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)
        return redirect(url_for('dashboard_bp.dashboard'))

    return render_template('register.html', form=form)

app/views/about_us_page.py
from flask import Blueprint, render_template

from app.views.auth import confirmed_required

about_us_page_bp = Blueprint("about_us_page_bp", __name__)


@about_us_page_bp.route("/about-us-page")
@confirmed_required
def about_us_page():
    return render_template("main/about_us_page.html", active_nav="about_us")

app/views/find_page.py
from datetime import datetime

from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, url_for
from flask_login import current_user

from app.forms import DateRequestForm
from app.models import DateProposal, ProposalStatus
from app.models.database import db
from app.models.user import User
from app.utils.algorithm import suggest_matches
from app.views.auth import confirmed_required

find_page_bp = Blueprint("find_page_bp", __name__)


@find_page_bp.route("/find-page/")
@confirmed_required
def find_page():
    return redirect(url_for("find_page_bp.find_page_invite"))

@find_page_bp.route("/find-page/profile/<int:user_id>")
@confirmed_required
def find_page_profile(user_id):
    date_request_form = DateRequestForm(message_label_text="Optional text attached to invite/reject")
    user = db.get_or_404(User, user_id)
    if user.id == current_user.id:
        return redirect(url_for("you_page_bp.you_page"))
        
    return render_template("profile.html", user=user, form=date_request_form, invite_only=True)

@find_page_bp.route("/find-page/invite")
@confirmed_required
def find_page_invite():
    date_request_form = DateRequestForm()
    is_requesting = True

    date_request_data = get_suggested_matches_data(app.config["INITIAL_SUGGESTION_NUMBER"])
    if not date_request_data:
        date_request_data = None

    return render_template(
        "main/find_page.html",
        date_request_data=date_request_data,
        form=date_request_form,
        is_requesting=is_requesting,
        redirect_buttons_set_data=redirect_buttons_set_data(),
        active_nav="find",
    )


@find_page_bp.route("/find-page/refill", methods=["POST"])
@confirmed_required
def refill():
    ignore_ids = [user["id"] for user in request.json]
    return get_suggested_matches_data(app.config["REFILL_SUGGESTION_NUMBER"], ignore_ids=ignore_ids)


def get_suggested_matches_data(limit: int, ignore_ids=[]) -> list[dict]:
    suggested_users = suggest_matches(db.session, current_user.id, limit, ignore_ids)
    result = []
    for user in suggested_users:
        result.append(
            {
                "id": user.id,
                "name": user.profile.name,
                "description": user.profile.description,
                "image_url": user.profile.profile_picture_url_or_default,
                "user_id" : user.id
            }
        )
    return result


@find_page_bp.route("/find-page/answear")
@confirmed_required
def find_page_answear():
    date_request_form = DateRequestForm()

    date_request_data = get_pending_invitations_data(current_user.id)
    is_requesting = False

    if not date_request_data:
        date_request_data = None

    return render_template(
        "main/find_page.html",
        date_request_data=date_request_data,
        form=date_request_form,
        is_requesting=is_requesting,
        redirect_buttons_set_data=redirect_buttons_set_data(),
        active_nav="find",
    )


def get_pending_invitations(user_id: int) -> list[DateProposal]:
    query = (
        db.select(DateProposal)
        .where(DateProposal.recipient_id == user_id)
        .where(DateProposal.date >= datetime.now().date())
        .where(DateProposal.status == ProposalStatus.proposed)
        .where(~DateProposal.proposer_id.in_(user.id for user in current_user.blocking))
    )
    return db.session.execute(query).scalars().all()


def get_pending_invitations_data(user_id):
    invitations = get_pending_invitations(user_id)
    result = []
    for invitation in invitations:
        result.append(
            {
                "id": invitation.id,
                "name": invitation.proposer.profile.name,
                "description": invitation.proposer.profile.description,
                "message": invitation.proposal_message,  # "" if invitation.proposal_message is None else invitation.proposal_message,
                "date": invitation.date.strftime(r"%Y-%m-%d"),
                "image_url" : invitation.proposer.profile.profile_picture_url_or_default,
                "user_id" : invitation.proposer.id
            }
        )
    return result


def redirect_buttons_set_data():
    return [
        {"url": url_for("find_page_bp.find_page_answear"), "text": "answear"},
        {"url": url_for("find_page_bp.find_page_invite"), "text": "matches"},
    ]

app/views/interaction.py
from datetime import datetime

from flask import Blueprint, request
from flask_login import current_user

from app import User, db
from app.forms import DateRequestForm
from app.models import DateProposal, ProposalStatus
from app.views.auth import confirmed_required

interaction_bp = Blueprint("interaction_bp", __name__)


@interaction_bp.route("/like/<int:user_id>", methods=["POST"])
@confirmed_required
def like(user_id):
    if user_id != current_user.id:
        user = db.get_or_404(User, user_id)
        if current_user in user.likers:
            user.likers.remove(current_user)
            db.session.commit()
        else:
            user.likers.append(current_user)
            db.session.commit()
        return "", 200
    return "", 400


@interaction_bp.route("/block/<int:user_id>", methods=["POST"])
@confirmed_required
def block(user_id):
    if user_id != current_user.id:
        user = db.get_or_404(User, user_id)
        if current_user in user.blockers:
            user.blockers.remove(current_user)
        else:
            user.blockers.append(current_user)
        db.session.commit()
        return "", 200
    return "", 400


@interaction_bp.route("/invite", methods=["POST"])
@confirmed_required
def invite():
    form = DateRequestForm()
    if form.validate_on_submit():
        user = db.get_or_404(User, form.id.data)
        proposal = DateProposal(
            proposer_id=current_user.id,
            recipient_id=form.id.data,
            date=form.date.data,
            proposal_message=form.message.data,
        )
        if user in current_user.blockers:
            proposal.status = ProposalStatus.ignored
        db.session.add(proposal)
        db.session.commit()
        return "", 200
    return form.errors, 400


@interaction_bp.route("/reject", methods=["POST"])
@confirmed_required
def reject():
    form = DateRequestForm()
    del form.message
    del form.date
    if form.validate_on_submit():
        user = db.get_or_404(User, form.id.data)
        current_user.rejected.append(user)
        db.session.commit()
        return "", 200
    return form.errors, 400


@interaction_bp.route("/accept", methods=["POST"])
@confirmed_required
def accept():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.accepted, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/reject-invitation", methods=["POST"])
@confirmed_required
def reject_invitation():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.rejected, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/ignore", methods=["POST"])
@confirmed_required
def ignore():
    form = DateRequestForm()
    del form.date
    del form.message
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.ignored)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/reschedule", methods=["POST"])
@confirmed_required
def reschedule():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.reschedule, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400

app/views/matches_page.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user

from app.models.user import User
from app.views.auth import confirmed_required

matches_page_bp = Blueprint("matches_page_bp", __name__)


@matches_page_bp.route("/matches-page")
@confirmed_required
def matches_page():
    return redirect(url_for("matches_page_bp.matches_page_sent"))


@matches_page_bp.route("/matches-page/sent")
@confirmed_required
def matches_page_sent():
    sent_by_self = current_user.profile.proposals_sent_by_self
    return render_template(
        "main/matches_page.html",
        proposals_data=sent_by_self,
        redirect_buttons_set_data=redirect_buttons_set_data(),
        active_nav="matches",
    )


@matches_page_bp.route("/matches-page/received")
def matches_page_received():
    proposals_considered_by_self = current_user.profile.proposals_considered_by_self
    return render_template(
        "main/matches_page.html",
        proposals_data=proposals_considered_by_self,
        redirect_buttons_set_data=redirect_buttons_set_data(),
        active_nav="matches",
    )


@matches_page_bp.route("/matches-page/dates")
@confirmed_required
def matches_page_dates():
    accepted_by_either = current_user.profile.accepted_proposals_by_either
    return render_template(
        "main/matches_page.html",
        proposals_data=accepted_by_either,
        redirect_buttons_set_data=redirect_buttons_set_data(),
        active_nav="matches",
    )


def redirect_buttons_set_data():
    return [
        {"url": url_for("matches_page_bp.matches_page_sent"), "text": "sent"},
        {"url": url_for("matches_page_bp.matches_page_received"), "text": "received"},
        {"url": url_for("matches_page_bp.matches_page_dates"), "text": "dates"},
    ]

app/views/you_page.py
from flask import Blueprint, jsonify, render_template, url_for
from flask_login import current_user

from app.views.auth import confirmed_required

you_page_bp = Blueprint("you_page_bp", __name__)


@you_page_bp.route("/you-page")
@confirmed_required
def you_page():
    liked = current_user.liking
    return render_template(
        "main/you_page.html", users=liked, pull_buttons_set_data=pull_buttons_set_data(), active_nav="you"
    )


@you_page_bp.route("/sub-you-page-liked")
@confirmed_required
def sub_you_page_liked():
    liked = current_user.liking
    if not liked:
        return jsonify({"html": render_template("components/this_list_is_empty.html")})
    return jsonify({"html": render_template("components/users_profile_briefs.html", users=liked)})


@you_page_bp.route("/sub-you-page-blocked")
@confirmed_required
def sub_you_page_blocked():
    blocked = current_user.blocking
    if not blocked:
        return jsonify({"html": render_template("components/this_list_is_empty.html")})
    return jsonify({"html": render_template("components/users_profile_briefs.html", users=blocked)})


def pull_buttons_set_data():
    return [
        {"jsCallBackIndicator": "switch-to-liked", "text": "liked"},
        {"jsCallBackIndicator": "switch-to-blocked", "text": "blocked"},
    ]

app/templates/main/about_us_page.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="solo-centered-column-under-top-bar about-us" >
        <h1>About Us</h1>
        <p>Nestled in the heart of the city, The Gourmet Bistro offers a culinary experience like no other. Our menu is a fusion of locally sourced ingredients and internationally inspired flavors, carefully crafted by our talented chefs. Whether you’re craving a classic steak or adventurous seafood, our dishes are prepared with attention to detail and the finest quality produce. We take pride in providing an ambiance that is both sophisticated and comfortable, ideal for a casual meal with friends or a special evening out.
        </p><br><p>
            Our Story
            The Gourmet Bistro was founded with the mission to bring together the best of local cuisine and global influences in an environment that welcomes everyone. Our founders, passionate about food and hospitality, envisioned a place where creativity meets tradition. The result is a vibrant menu that celebrates diversity, offering something for every palate. From fresh, light salads to hearty mains, our dishes are designed to cater to a wide range of tastes and dietary preferences. Each meal is a reflection of our commitment to great food and even better company.
        </p><br><p>
            Exceptional Dining Experience
            Our commitment to quality extends beyond the kitchen. The restaurant’s warm and inviting interior features elegant decor, creating the perfect backdrop for an unforgettable meal. The open kitchen allows diners to watch our chefs work their magic, adding an extra layer of excitement to your dining experience. With attentive service and an extensive wine list to complement every dish, dining at The Gourmet Bistro is an experience you’ll want to relive time and again.
        </p><br> <p>    
            Join Us Today
            Whether you're celebrating a special occasion or simply looking to enjoy a delicious meal, The Gourmet Bistro welcomes you with open arms. Make a reservation today and treat yourself to an unforgettable dining experience that will leave you coming back for more.
            
            </p>
    </div>
{% endblock %}

app/templates/main/base.html
{% extends 'main/imports_base.html' %}
{% block imports_extension %}
    <header>
        <nav>
            <ul>
                <li></li>
                <li><a href="{{ url_for('find_page_bp.find_page_invite') }}" class='nav-link {% if active_nav=="find" %}active{% endif %}' id='nav-find'>Find</a></li>
                <li><a href="{{ url_for('matches_page_bp.matches_page') }}" class='nav-link {% if active_nav=="matches" %}active{% endif %}' id='nav-matches'>Invitations</a></li>
                <li><a href="{{ url_for('find_page_bp.find_page_invite') }}" class='nav-link' id='nav-logo'>

                    <img src="{{url_for('static', filename='images/lets-go-out-logo.png')}}" class="base-logo" alt="Company Icon">
                </a></li>
                <li><a href="{{ url_for('you_page_bp.you_page') }}" class='nav-link {% if active_nav=="you" %}active{% endif %}' id='nav-you'>You</a></li>
                <li><a href="{{ url_for('about_us_page_bp.about_us_page') }}" class='nav-link {% if active_nav=="about_us" %}active{% endif %}' id='nav-about-us'>About us</a></li>
                <li><a href="{{ url_for('auth_bp.logout') }}" class='nav-link' id='nav-about-us'>Logout</a></li>
                
            </ul>
        </nav>
    </header>
    
        {% block content %}
        {% endblock %}

{% endblock %}

app/templates/main/find_page.html
{% extends 'main/base.html' %}

{% block content %}
    <meta id="refill-path" data-path="{{ url_for('find_page_bp.refill') }}">
    <meta id="invite-path" data-path="{{ url_for('interaction_bp.invite') }}">
    <meta id="reject-path" data-path="{{ url_for('interaction_bp.reject') }}">
    <meta id="accept-path" data-path="{{ url_for('interaction_bp.accept') }}">
    <meta id="reject-invitation-path" data-path="{{ url_for('interaction_bp.reject_invitation') }}">
    <meta id="ignore-path" data-path="{{ url_for('interaction_bp.ignore') }}">
    <meta id="reschedule-path" data-path="{{ url_for('interaction_bp.reschedule') }}">
    <main class="solo-centered-column-under-top-bar">

        {% include 'components/set_of_redirect_buttons.html' %}
        

        {% if date_request_data != None %}
        <div class="date-invitation-card outline"  id="profile-block" {% if not date_request_data %} style="display: none" {% endif %}>
            <div class="fill-width centered-column gap-top-45">
                <img src="{{date_request_data[0].image_url}}" alt="Profile picture" class="circular-avatar-big light-shadow" id="profile-img"> 
                <h1 class="push-to-bottom gap-top-15 text-shadow" id="name">{{date_request_data[0].name}}</h1>
            </div>
            {% with url=url_for('find_page_bp.find_page_profile', user_id=date_request_data[0].user_id), text='See More', width='100px', font_size='medium', id='see-profile' %}
            {% include 'components/button.html' %}
            {% endwith %}
            <div class="gap-top-15"></div>
            {% include 'components/date_request.html' %}
            
        </div>
        {% endif %}
        <div class="centered-column" id="empty-block" {% if date_request_data %} style="display: none" {% endif %}>
            {% include 'components/no_matches_found.html' %}
        </div>
    </main>

    <script src="{{ url_for('static', filename='find_page_logic.js')}}"></script>

    {% if is_requesting %}
    <script>
        $(function(){
            set_cache(JSON.parse('{{ date_request_data | tojson | safe}}'))
            prepare_invite()
            next_user()
        })     
    </script>
    {% else %}
    <script>
        $(function(){
            set_cache(JSON.parse('{{ date_request_data | tojson | safe}}'))
            prepare_answear()
            next_invitation()
        })
        
    </script>
    {% endif %}


{% endblock %}

app/templates/main/imports_base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet"
              href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    
        {% block imports_extension %}
        {% endblock %}
    
    
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
    <script
            src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>    
</body>
</html>

app/templates/main/matches_page.html
{% extends 'main/base.html' %}

{% block content %}
    <main class="solo-centered-column-under-top-bar">
        {% include 'components/set_of_redirect_buttons.html' %}
        {% if not proposals_data %}
            <div class="centered-height-with-nav">{% include 'components/this_list_is_empty.html' %}</div>
        {% else %}
        
        <div class="centered-column outline">
            {% for proposal_data in proposals_data %}
            {% if proposal_data.proposer_id == current_user.id %}
            {% with 
                user=proposal_data.recipient,
                proposal=proposal_data
            %}
            {% include 'components/profile_brief.html' %}
            {% endwith %}
            {% else %}
            {% with 
                user=proposal_data.proposer, 
                proposal=proposal_data
            %}
            {% include 'components/profile_brief.html' %}
            {% endwith %}
            {% endif %}
            
            {% endfor %}
        </div>

        {% endif %}
    </main>
{% endblock %}

app/templates/main/you_page.html
{% extends 'main/base.html' %}

{% block content %}
    <main class="row scrollable-panes-container solo-centered-column-under-top-bar">
        <div class="centered-column outline scrollable-pane you-left-col" style="width: 400px">
            <div class="save">{% include 'components/set_of_pull_buttons.html' %}</div>
            {% if users == [] %}
            {% include 'components/this_list_is_empty.html' %}
            {% else %}
            {% for user in users %}
                {% include 'components/profile_brief.html' %}
            {% endfor %}
            {% endif %}
        </div>
        <div class="centered-column outline scrollable-pane you-right-col">
        <div class="row space-between fill-width"><div style="display: hidden"></div>
            <i id="edit-profile-icon" class="fas fa-edit fa-2x light-color labeled-icon"></i>
        </div>
            {% with user=current_user %}
            {% include "components/full_profile_info.html" %}
            {% endwith %}
        </div>
    </main>
    <script>
        const likedPath = "{{url_for('you_page_bp.sub_you_page_liked')}}";
        const blockedPath = "{{url_for('you_page_bp.sub_you_page_blocked')}}";
        const editProfilePath = "{{url_for('profile_manager_bp.profile_manager')}}";
    </script>
    <script src="{{ url_for('static', filename='you_page.js')}}"></script>
                
{% endblock %}