app/forms/account_manager_form.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SubmitField
from wtforms.validators import Email, EqualTo, InputRequired, Length

from app.config import MINIMUM_PASSWORD_LENGTH
from app.forms.validators import email_own_or_unique, password_correct


class AccountManagerForm(FlaskForm):
    email = EmailField(
        "Email",
        [
            InputRequired(message="Email address is required."),
            Email(message="Please provide a correct email address."),
            email_own_or_unique
        ],
    )
    old_password = PasswordField(
        "Current password:",
        [InputRequired(message="Please input your current password."), password_correct],
    )
    new_password = PasswordField(
        "New password",
        [
            InputRequired(message="Please input new password."),
            Length(min=MINIMUM_PASSWORD_LENGTH, message="Password is too short!"),
        ],
    )
    new_confirm = PasswordField(
        "Confirm new password",
        [
            InputRequired(message="Please confirm the new password."),
            EqualTo(
                "new_password",
                message="Password confirmation must equal the password.",
            ),
        ],
    )
    submit = SubmitField("Change")

app/forms/profile_manager_form.py
import json

from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from flask_wtf.form import _Auto
from wtforms import IntegerField, RadioField, SelectMultipleField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, InputRequired, NumberRange, Optional

from app import db
from app.forms.validators import age_limit
from app.models import Interest


class ProfileManagerForm(FlaskForm):
    name = StringField("Name", [InputRequired(message="Name must not be empty.")])
    gender = RadioField("Gender")
    description = TextAreaField("Description", [])
    gender_preferences = SelectMultipleField("Gender preferences")
    year_of_birth = IntegerField("Year of birth", [InputRequired(message="Year of birth is required."), age_limit])
    lower_difference = IntegerField(
        "Lower Difference",
        [
            InputRequired(message="Age difference is required."),
            NumberRange(min=0, max=30, message="Age difference cannot be negative."),
        ],
    )
    upper_difference = IntegerField(
        "Upper Difference",
        [
            InputRequired(message="Age difference is required."),
            NumberRange(min=0, max=30, message="Age difference cannot be negative."),
        ],
    )
    photo = FileField("Profile Photo", validators=[Optional()])
    submit = SubmitField("Change")
    interests = StringField("Interests", validators=[Optional()])

    @property
    def interests_as_list(self):
        return [db.get_or_404(Interest, int(single["id"])) for single in json.loads(self.interests.data)]

app/views/interaction.py
from datetime import datetime

from flask import Blueprint, request
from flask_login import current_user

from app import User, db
from app.forms import DateRequestForm
from app.models import DateProposal, ProposalStatus
from app.views.auth import confirmed_required

interaction_bp = Blueprint("interaction_bp", __name__)


@interaction_bp.route("/like/<int:user_id>", methods=["POST"])
@confirmed_required
def like(user_id):
    if user_id != current_user.id:
        user = db.get_or_404(User, user_id)
        if current_user in user.likers:
            user.likers.remove(current_user)
            db.session.commit()
        else:
            user.likers.append(current_user)
            db.session.commit()
        return "", 200
    return "", 400


@interaction_bp.route("/block/<int:user_id>", methods=["POST"])
@confirmed_required
def block(user_id):
    if user_id != current_user.id:
        user = db.get_or_404(User, user_id)
        if current_user in user.blockers:
            user.blockers.remove(current_user)
        else:
            user.blockers.append(current_user)
        db.session.commit()
        return "", 200
    return "", 400


@interaction_bp.route("/invite", methods=["POST"])
@confirmed_required
def invite():
    form = DateRequestForm()
    if form.validate_on_submit():
        user = db.get_or_404(User, form.id.data)
        proposal = DateProposal(
            proposer_id=current_user.id,
            recipient_id=form.id.data,
            date=form.date.data,
            proposal_message=form.message.data,
        )
        if user in current_user.blockers:
            proposal.status = ProposalStatus.ignored
        db.session.add(proposal)
        db.session.commit()
        return "", 200
    return form.errors, 400


@interaction_bp.route("/reject", methods=["POST"])
@confirmed_required
def reject():
    form = DateRequestForm()
    del form.message
    del form.date
    if form.validate_on_submit():
        user = db.get_or_404(User, form.id.data)
        current_user.rejected.append(user)
        db.session.commit()
        return "", 200
    return form.errors, 400


@interaction_bp.route("/accept", methods=["POST"])
@confirmed_required
def accept():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.accepted, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/reject-invitation", methods=["POST"])
@confirmed_required
def reject_invitation():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.rejected, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/ignore", methods=["POST"])
@confirmed_required
def ignore():
    form = DateRequestForm()
    del form.date
    del form.message
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.ignored)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400


@interaction_bp.route("/reschedule", methods=["POST"])
@confirmed_required
def reschedule():
    form = DateRequestForm()
    del form.date
    if form.validate_on_submit():
        proposal = db.get_or_404(DateProposal, form.id.data)
        if proposal.recipient_id == current_user.id:
            proposal.change_status(ProposalStatus.reschedule, form.message.data)
            db.session.commit()
            return "", 200
        return "", 401
    return form.errors, 400

app/views/profile.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user

from app import User, db
from app.forms.date_request_form import DateRequestForm
from app.views.auth import confirmed_required

profile_bp = Blueprint("profile_bp", __name__)


@profile_bp.route("/profile/<int:user_id>")
@confirmed_required
def profile(user_id):
    date_request_form = DateRequestForm(message_label_text="Optional text attached to invite/reject")
    invite_only = request.args.get('invite_only', default=True)
    user = db.get_or_404(User, user_id)
    if user.id == current_user.id:
        return redirect(url_for("you_page_bp.you_page"))
        
    return render_template("profile.html", user=user, form=date_request_form, invite_only=invite_only)

app/views/profile_manager.py
import json
import logging
import os

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user
from sqlalchemy.exc import IntegrityError
from werkzeug.utils import secure_filename

from app import db
from app.forms import AccountManagerForm, ProfileManagerForm
from app.models import Gender, Photo
from app.models.interest import Interest
from app.views.auth import confirmed_required

logger = logging.getLogger(__name__)

profile_manager_bp = Blueprint("profile_manager_bp", __name__)


@profile_manager_bp.route("/profile-manager", methods=["GET", "POST"])
@confirmed_required
def profile_manager():
    form = ProfileManagerForm()
    account_form = AccountManagerForm()

    form.gender_preferences.choices = [(gender.name, gender.value) for gender in Gender]
    form.gender.choices = [(gender.name, gender.value) for gender in Gender]

    if request.method == "GET":
        return render_template("profile_manager.html", form=form, account_form=account_form, account_change=False)

    if form.validate_on_submit():
        name = form.name.data
        gender = Gender[form.gender.data]
        year_of_birth = form.year_of_birth.data
        description = form.description.data.strip()
        lower_difference = form.lower_difference.data
        upper_difference = form.upper_difference.data
        gender_preferences = [Gender[gp] for gp in form.gender_preferences.data]
        interests = [db.get_or_404(Interest, int(single["id"])) for single in json.loads(form.interests.data)]

        if form.photo.data:
            photo = form.photo.data
            handle_photo_upload(photo, current_user)

        current_user.profile.name = name
        current_user.profile.gender = gender
        current_user.profile.year_of_birth = year_of_birth
        current_user.profile.description = description
        current_user.matching_preferences.gender_preferences = gender_preferences
        current_user.matching_preferences.lower_difference = lower_difference
        current_user.matching_preferences.upper_difference = upper_difference
        current_user.profile.interests = interests

        try:
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
            logger.error(e)
        return redirect(url_for("you_page_bp.you_page"))

    return render_template("profile_manager.html", form=form, account_form=account_form, account_change=False)


def handle_photo_upload(photo, user) -> Photo:
    if user.profile.photo:
        old_photo_path = user.profile.photo.os_photo_url
        if os.path.exists(old_photo_path):
            os.remove(old_photo_path)
        else:
            logger.error(f"Photo path {old_photo_path} does not exist")

        db.session.delete(user.profile.photo)

    extension = secure_filename(photo.filename).split(".")[-1]
    new_photo = Photo(profile=user.profile, file_extension=extension)

    db.session.add(new_photo)
    db.session.commit()

    photo.save(new_photo.os_photo_url)

    user.profile.photo = new_photo

    return new_photo


@profile_manager_bp.route("/account-manager", methods=["POST"])
@confirmed_required
def account_manager():

    account_form = AccountManagerForm()

    if account_form.validate_on_submit():
        current_user.set_password(account_form.new_password.data)
        current_user.email = account_form.email.data
        try:
            db.session.commit()
        except IntegrityError as e:
            db.session.rollback()
        return redirect(url_for("you_page_bp.you_page"))

    form = ProfileManagerForm()

    form.gender_preferences.choices = [(gender.name, gender.value) for gender in Gender]
    form.gender.choices = [(gender.name, gender.value) for gender in Gender]

    return render_template("profile_manager.html", form=form, account_form=account_form, account_change=True)

app/templates/account_manager.html
<div class="form-container">

    <form action="{{ url_for('profile_manager_bp.account_manager') }}" method="POST">
        
        {{ account_form.csrf_token }}

        {% with type="email", name="email", label="Email", value=current_user.email, input=account_form.email%}
        {% include 'components/partials/input_field.html' %}
        {% endwith %}

        {% with type="password", name="old_password", label="Current password", input=account_form.old_password %}
        {% include 'components/partials/input_field.html' %}
        {% endwith %}

        {% with type="password", name="new_password", label="New password", input=account_form.new_password %}
        {% include 'components/partials/input_field.html' %}
        {% endwith %}
    
        {% with type="password", name="new_confirm", label="Confirm new password", input=account_form.new_confirm %}
        {% include 'components/partials/input_field.html' %}
        {% endwith %}
        
        
        <button type="submit" >Change</button>
    
    </form>

</div>

app/templates/profile.html
{% extends 'main/base.html' %}
{% block content %}
    <meta id="like-path" data-path="{{ url_for('interaction_bp.like', user_id = user.id) }}">
    <meta id="block-path" data-path="{{ url_for('interaction_bp.block', user_id = user.id) }}">
    <meta id="invite-path" data-path="{{ url_for('interaction_bp.invite') }}">
    <meta id="reject-path" data-path="{{ url_for('interaction_bp.reject') }}">

    <main class="solo-centered-column-under-top-bar">
        <div class="centered-column outline" style="width: 400px">
            <div class="row space-between fill-width">
                {% if not user.liked_by_main_user %}
                    <i class="labeled-icon far fa-star text-color fa-2x" id="like-button" value="Like"></i>
                {% else %}
                    <i class="labeled-icon fas fa-star fa-2x" id="like-button" value="Like"></i>
                {% endif %}
                {% if not user.blocked_by_main_user %}
                    <i class="labeled-icon fas fa-ban text-color fa-2x" id="block-button" value="Block"></i>
                {% else %}
                    <i class="labeled-icon fas fa-ban fa-2x" id="block-button" value="Block"></i>
                {% endif %}
            </div>
            {% include 'components/full_profile_info.html' %}
            {% with is_requesting = true %}
            {% include 'components/date_request.html' %}
            {% endwith %}
        </div>
    </main>
    <script src="{{ url_for('static', filename='profile_logic.js')}}"></script>
    <script>
        id_hidden_input = document.querySelector("#id-hidden")
        id_hidden_input.value = '{{ user.id }}'
        document.querySelector("#message-input").value = ""
        document.querySelector("#date-input").value = ""
    </script>

{% endblock %}

app/templates/profile_manager.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile Manager</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/Dogfalo/materialize@master/extras/noUiSlider/nouislider.css">
    <link rel="stylesheet"
          href="https://gist.githubusercontent.com/alexventuraio/4d0c725c34941fa42361350dcb43731f/raw/9364364f491288ffa1c1efbe796a44e07c16908d/sponsor.matchxperience.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/Dogfalo/materialize@master/extras/noUiSlider/nouislider.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>
<div class="form-container">
    <h1>Profile Manager</h1>
    <form action="{{ url_for('you_page_bp.you_page') }}" method="get" class="gap-top-15">
        <button type="submit" class="primary-background-color text-color fill-width shadow">Return</button>
    </form>
    <form action="{{ url_for('profile_manager_bp.profile_manager') }}" method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}

        {% with value=current_user.profile.profile_picture_url_or_default, input=form.photo %}
        {% include "components/partials/profile_photo.html" %}
        {% endwith %}

        {% with name="name", label="Name", value=current_user.profile.name, input=form.name%}
        {% include 'components/partials/input_field.html' %}
        {% endwith %}

        {% with value_chosen=current_user.profile.gender.name, choices=form.gender.choices, input=form.gender %}
        {% include "components/partials/gender_options.html" %}
        {% endwith %}

        {% with type="number", name="year_of_birth", label="Year of Birth", value=current_user.profile.year_of_birth, input=form.year_of_birth %}
            {% include 'components/partials/input_field.html' %}
        {% endwith %}

        {% with name="description", label="Profile Description", value=current_user.profile.description, input=form.description %}
            {% include "components/partials/textarea_field.html" %}
        {% endwith %}

        {% with interests=current_user.profile.interests %}
            {% include "components/interests_choosing.html" %}
        {% endwith %}

        <div class="input-field">
            <p>
                <label>Gender Preferences</label>
                {% for name, value in form.gender_preferences.choices %}
                <label>
                    <input type="checkbox"
                           name="gender_preferences"
                           value="{{ name }}"
                           {% if current_user.has_preference_for(name) %}checked{% endif %}/>
                    <span>{{ value }}</span>
                </label>
                {% endfor %}
            </p>
        </div>
        {% with input = form.gender_preferences %}
        {% include "components/partials/error_list.html" %}
        {% endwith %}
        
        {% with lower_difference=current_user.matching_preferences.lower_difference , upper_difference=current_user.matching_preferences.upper_difference, input1 = form.lower_difference, input2 = form.upper_difference %}
            {% include "components/partials/age_preferences.html" %}
        {% endwith %}

        <br>
        <button type="submit" >Save</button>
    </form>

    <details class="gap-top-15" id="account_manager_tab" {% if account_change %} open {% endif %}>
        <summary>Account manager</summary>
        {% include "account_manager.html" %}
    </details>    
</div>
<script src="{{ url_for('static', filename='scripts.js') }}"></script>
{% if account_change %}
<script>
    document.getElementById('account_manager_tab').scrollIntoView();
</script>
{% endif %}
</body>
</html>